name: app
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - typing_extensions

  - pytorch=2.5.1
  - pytorch-cuda=12.4

  # Add cuda-version to satisfy __cuda
  - cuda-version=12.4

  # DDP/NCCL (usually comes transitively, but let's keep it explicit)
  - nccl